# Name of workflow
name: CI CD GHA workflow
env: 
    deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

# Trigger workflow on all pull requests
on:
  pull_request: 
    types: closed
    branches:
      - main

# Jobs to carry out
jobs:
    render-deploy: 
        runs-on: ubuntu-latest
        strategy: 
            matrix: 
                node-version: [18.X, 20.X, 22.X]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with: 
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Render Deploy Action
              run: curl "$deploy_url"